nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.0.2.cjs

enableGlobalCache: false

compressionLevel: mixed

enableTelemetry: false

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard

packageExtensions:
  "@types/node@*":
    peerDependenciesMeta:
      typescript:
        optional: true
